# Generated by Django 3.0.5 on 2020-11-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(null=True, unique='name'),
        ),
        migrations.AddField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(null=True, unique='name'),
        ),
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='content.Categories'),
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='content.Genres'),
        ),
        migrations.AddField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='year published'),
        ),
    ]
