# Generated by Django 3.0.5 on 2020-11-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201109_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='year',
        ),
    ]
