# Generated by Django 3.0.5 on 2020-11-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_titles_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
