# Generated by Django 3.0.5 on 2020-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_titles_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
